---
# tasks file for sbaerlocher.remote-desktop

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.TerminalServer::TS_DISABLE_CONNECTIONS
- name: Allow users to connect remotely by using Remote Desktop Services
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    name: fDenyTSConnections
    data: 00000000
    type: dword
    state: "{{ 'present' if remote_desktop_enabled else 'absent' }}"
  register: register_remote_desktop_enabled
  tags:
    - configuration

- name: Firewall Enable rule for Remote Desktop Services
  win_shell: Enable-NetFirewallRule -DisplayGroup "Remotedesktop"
  when: remote_desktop_enabled and register_remote_desktop_enabled.changed
  tags:
    - configuration

- name: Firewall Disable rule for Remote Desktop Services
  win_shell: Disable-NetFirewallRule -DisplayGroup "Remotedesktop"
  when: not remote_desktop_enabled and register_remote_desktop_enabled.changed
  tags:
    - configuration

- name: Set then Remote Desktop Port
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
    name: PortNumber
    data: "{{ remote_desktop_port }}"
    type: dword
  tags:
    - configuration

- name: Firewall rule to allow RDP on TCP port 3389
  win_firewall_rule:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    localport: "{{ remote_desktop_port }}"
    action: allow
    direction: in
    protocol: "{{ item.protocol }}"
    profiles: domain,private,public
    state: present
    enabled: "{{ 'true' if remote_desktop_enabled else 'false' }}"
    service: termservice
    program: C:\Windows\system32\svchost.exe
  with_items:
    - name: Remotedesktop - Benutzermodus (TCP eingehend)
      description: Eingehende Regel f체r den Remotedesktopdienst, die RDP-Datenverkehr zul채sst. [TCP 3389]
      protocol: tcp
    - name: Remotedesktop - Benutzermodus (UDP eingehend)
      description: Eingehende Regel f체r den Remotedesktopdienst, die RDP-Datenverkehr zul채sst [UDP 3389]
      protocol: udp
  tags:
    - configuration

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.TerminalServer::TS_SECURITY_LAYER_POLICY
- name: Require use of specific security layer for remote (RDP) connections
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    name: SecurityLayer
    data: "{{ remote_desktop_securitylayer }}"
    type: dword
    state: "{{ 'present' if remote_desktop_enabled else 'absent' }}"
  tags:
    - configuration

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.TerminalServer::TS_ENCRYPTION_POLICY
- name: Set client connection encryption level
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    name: MinEncryptionLevel
    data: "{{ remote_desktop_minencryptionLevel }}"
    type: dword
    state: "{{ 'present' if remote_desktop_enabled else 'absent' }}"
  tags:
    - configuration
