---
# tasks file for sbaerlocher.remote-desktop

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.TerminalServer::TS_DISABLE_CONNECTIONS
- name: Allow users to connect remotely by using Remote Desktop Services
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    name: fDenyTSConnections
    data: 00000000
    type: dword
    state: "{{ 'present' if remote_desktop_enabled else 'absent' }}"
  tags:
    - configuration

- name: Firewall Enable rule for Remote Desktop Services
  win_shell: Enable-NetFirewallRule -DisplayGroup "Remotedesktop"
  when: remote_desktop_enabled
  tags:
    - configuration

- name: Firewall Disable rule for Remote Desktop Services
  win_shell: Disable-NetFirewallRule -DisplayGroup "Remotedesktop"
  when: not remote_desktop_enabled
  tags:
    - configuration
